### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by mwarning**
Hi,

here are various changes from FreiFunkMuenster/meshviewer and freifunk-bielefeld/meshviewer.

Changes:
* german text elements
* do not show titles for empty stat tables
* allow link to community webpage in siteNames variable

TODO:
- merge conflicts..

### CODE REVIEW

**Comment by rubo77** [comment]
could it be, that you compared your branch with the wrong upstream branch?

this seems a bit much for one pull request ;)

**Comment by mwarning** [comment]
Well, it contains the changes from FreiFunkMuenster/meshviewer as well. But their upstream merge plans does not seem to progress forward since over a year ago. That is why I choose this route.

To be fair, they merge my changes into FreiFunkMuenster/meshviewer. But in the end, I do not think it matters much from where the merge request comes from. :-)

**Comment by rubo77** [comment]
Still, you choose the wrong branch: ffnord:dev

your branch is a continuation of ffnord:master, so you have to start over again, to get this merged.

Your branch is a split-off of 83b2a67cf406a80e855d3b57a6bade6b7812364a in the master tree

**Comment by mwarning** [comment]
@rubo77 ah, thanks. - Changed :-)

**Comment by rubo77** [comment]
can you resolve the readme conflict?

**Comment by mwarning** [comment]
@rubo77 conflict resolved. But most readme changes need to be reverted back to ffnord/meshviewer. That can be done afterwards, of course.

**Comment by rubo77** [comment]
If you want to get this PR accepted, you should rework the README, so it is not Bielefeld specific any more

**Comment by mwarning** [comment]
done

**Comment by rubo77** [comment]
# This Fork is not maintained!

This was the original Branch of the Meshviewer, but it is not further developed here. There are two main branches, that are worked on. 

Please use https://github.com/ffrgb/meshviewer or https://github.com/hopglass/hopglass

If you are a developer, please consider joining one of those follow-up projects.

**Comment by mwarning** [comment]
@rubo77 most changes have been included in ffrgb/meshviewer, this merge request can be closed.

**Pull request closed without merging**
