### PR TITLE
add coord picker in map

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lost-tty** [comment]
This needs a much more descriptive commit message.

**Comment by ghost** [comment]
better?

**Comment by lost-tty** [comment]
The message should explain the feature and why it is useful. It should also be prefixed with the module it affects (i.e. "map: add coordinates picker").

**Comment by ghost** [comment]
ping @tcatm okay like this?

**Comment by lost-tty** [comment]
I think this might work. If someone feels like testing and merging this, please go ahead :)

**Comment by ghost** [comment]
This should fix the first click issue according to the author.

**Pull request merged**
