### PR TITLE
Header in all-nodes view shorter on small screens

### PR DESCRIPTION
**Pull request by rubo77**
This will change the label on top of the list for all nodes to just the first Letter "U" for "Uptime" and "C" for "Clients"

### CODE REVIEW

**Comment by lost-tty** [comment]
I don't really like this patch. It adds a `config.json` for no apparent reason and it hardcodes the columns used within Javascript to those in CSS.

**Comment by rubo77** [comment]
sure, the config.json was a mistake.

I thought about how to solve the issue to shorten the table headers on small screens with just CSS, which I would prefer, because it takes action when you resize the screen.

If we would like to use the first letter of each column without hardcoding, We would have to use javascript and a kid of resize-detection to change it on the fly when resizing the screen. Would that be a better solution?

Or I just got another Idea:  
We could turn the labels by 90° on narrow screens

**Comment by jplitza** [comment]
Only showing the first letter isn't that hard, rotating the titles is harder I think: https://jsfiddle.net/o0dz6ufu/

**Comment by lost-tty** [comment]
Which resolutions and screensizes are affected by this anyway?

**Comment by rubo77** [comment]
Te labels don't fit on 320px with phone screens

jplitzas solution is working nice (with `th:first-letter, th:first-child`)

I also already solved rotating here. #19

**Pull request closed without merging**
