### PR TITLE
Don't wrap the sidebar's right column

### PR DESCRIPTION
**Pull request by mruettgers**

### CODE REVIEW

**Comment by lost-tty** [comment]
Could you explain why this is needed? not(first-child) would trigger all but the first column instead of just the right most one.

**Comment by mruettgers** [comment]
I can't reproduce it at the moment.
The content of the column containing the time a node has been part of the network has been wrapped for extra-long node names. I'll close the PR for now as there's some more investigation needed.

**Comment by jplitza** [comment]
Are you sure this isn't fixed by #20?

**Comment by mruettgers** [comment]
You're right, this seems to be fixed.

**Pull request closed without merging**
