### PR TITLE
nodelist: show #links of node

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lost-tty** [comment]
I wonder whether we should call it "Neighbours" instead of Links?

**Comment by ghost** [comment]
I renamed it to 'Neighbour' and noticed that it doesn't fit on the screen on small mobile devices. I will look into a solution by shortening the names to the first letter on very small screens.

**Comment by rubo77** [comment]
This will be the solution so it will fit: https://github.com/ffnord/meshviewer/pull/18

**Comment by lost-tty** [comment]
What do you think about introducing a full-width nodelist where even more data columns could be shown?

**Comment by rubo77** [comment]
A full list with more data would be great! (Like in the old ffmap-d3)

**Comment by Little-Ben** [comment]
This issue also deals with data security.
Columns shown on such a page are more present for ordinary people than they are in alfred. 
Of course every thing is reachable through alfred (or its successor), but than it is not a simple click on a worldwide reachable web interface.

Could this be configurable? 
Define relevant columns in config.json or even if the whole page is offered? So every community could decide which further columns/alfred facts should be shown.

**Comment by lost-tty** [comment]
@Little-Ben I think the contact field will stay configurable (the code is already) in place.

**Pull request closed without merging**
